### ISSUE TITLE
cannot deploy erc20 wasm with web3 api

### ISSUE THREAD

**Issue by eee4017** [ParaState/frontier#12]
**Description**

When trying to deploy the ewasm erc20 contract with web3 in `web3/erc20.js`, the deployment failed due to out-of-gas error.

**Steps to Reproduce**

1. set up nodes with the steps in [validator-set.md](https://github.com/ParaState/frontier/blob/ssvm/docs/validator-set/validator-set.md)
2. `node erc20.js`
3. **error: The contract code couldn't be stored, please check your gas limit.**
4. gaslimit should be specified in `web3.eth.sendTransaction`,  I passed `gas:99999999` into API.
5. **error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.**

**Comment by CaptainVincent** [comment]
@eee4017 you can try newer instructions in [validator-set.md](https://github.com/ParaState/frontier/blob/ssvm/docs/validator-set/validator-set.md). 
This issue should have been solved at commit 848b7259f9ef8fd3e246fd5f98acd223222bc25e.

If you'd like to use more simple way to test deploy smart contracts on frontier chain, 
you could try [launch node instructions in the wiki](https://github.com/ParaState/frontier/wiki/Run-ERC20-tests).
This will reduce the effort that you must have to launch two nodes for start generate block.
