### ISSUE TITLE
Not able to initiate a node . terminates with error 

### ISSUE THREAD

**Issue by biswajitjei02** [ParaState/frontier#15]
i have installed all dependencies asper the doc . i have Ubuntu 20.04 . Tried to  initialized the node. but i am getting error 
`Error: Input("Error opening spec file: No such file or directory (os error 2)")`

![image](https://user-images.githubusercontent.com/38404689/119219458-575de780-bb03-11eb-843b-7f5622367875.png)

**Comment by ogsells1** [comment]
The same for me at this point

 cargo run --release --bin frontier-template-node -- \
  --execution=Native \
  --base-path ./data \
  --chain ./2021-04-22-spec-raw.json \
  --port 30333 \
  --rpc-port 9933 \
  --ws-port 9944 \
  --validator \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --name '<Your Node Name>' \
  --bootnodes /ip4/13.67.57.72/tcp/30333/p2p/12D3KooWNwpkJk3f4fUEc9cjSzLC5xE3opf25pjt7izfNGc1v5Tu 

// Digital Ocean

**Comment by mrworksome** [comment]
The same for me at this point

Run in Hetzner Ubuntu18.04
<img width="827" alt="Screenshot 2021-05-23 at 04 55 14" src="https://user-images.githubusercontent.com/46965627/119245578-11e0ff00-bb83-11eb-844d-423da53b1212.png">

**Comment by hydai** [comment]
Thanks @biswajitjei02 , @ogsells1 , @mrworksome 

This issue is fixed in #16 
Also, we updated the wiki for the new chain file path.
