### ISSUE TITLE
Sync balance between substrate & pallet-vm

### ISSUE THREAD

**Issue by dm4** [ParaState/frontier#19]
The substrate balance for substrate account address is not sync to the corresponding EVM account address at pallet-vm.

Current conversion from substrate account to EVM account:
https://github.com/ParaState/frontier/blob/ssvm/frame/vm/src/lib.rs#L169-L184

Current conversion from EVM account to substrate account:
https://github.com/ParaState/frontier/blob/ssvm/frame/vm/src/lib.rs#L200-L209

We need to find a way to sync balance between substrate & EVM accounts.

**Comment by CaptainVincent** [comment]
這是目前 charge gas fee 的架構, ① ② 是有想到可能可以改進的地方
![IconFundationEnhance](https://user-images.githubusercontent.com/12159865/120127027-b51fbd00-c1f0-11eb-894c-7ceaec91e8dd.jpg)

**Comment by yanganto** [comment]
The upstream VM frame is upgraded to frame v2, should we take this into consideration?
https://github.com/paritytech/frontier/pull/380

**Comment by CaptainVincent** [comment]
> paritytech#380

In progress on migrate branch.
still working on fix remain ts-tests fail cases.

**Comment by CaptainVincent** [comment]
Update: Merge official frontier/master latest version 6e2e908 into ssvm done in #20
(including [paritytech#380](https://github.com/paritytech/frontier/pull/380))

**Comment by yanganto** [comment]
After discussion, the issue is invalid and there will be other issues to address the business problem.

#27 #28 #29
