### ISSUE TITLE
Missing directory

### ISSUE THREAD

**Issue by B1boid** [ParaState/frontier#47]
**Description**

I tried to run ParaState node and got an error when I typed the command:

```
cargo run --release --bin frontier-template-node -- \
  --execution=Native \
  --base-path ./data \
  --chain ./specs/2021-04-22-spec-raw.json \
  --port 30333 \
  --rpc-port 9933 \
  --ws-port 9944 \
  --validator \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --name '<Your Node Name>' \
  --bootnodes /ip4/13.67.57.72/tcp/30333/p2p/12D3KooWNwpkJk3f4fUEc9cjSzLC5xE3opf25pjt7izfNGc1v5Tu
```
```
Error: Input("Error opening spec file: No such file or directory (os error 2)")
```

**Steps to Reproduce**

Just follow official guide https://github.com/ParaState/frontier/wiki/ParaState-Testnet-Node-Setup-Guideline

**How to fix this bug**

As I understand it, the problem occurs due to the absence of the _specs_ folder on github in the branch testnet-2021-04-22

So I solve fix this bug, by adding _specs_ folder with files from default branch https://github.com/ParaState/frontier

I made pull request with this solution: https://github.com/ParaState/frontier/pull/46

**Comment by hydai** [comment]
cc @dm4 

I believe this is fixed in the `ssvm` branch. However, it didn't merge back to the `testnet-2021-04-22` branch. Could you please rebase it to fix this?

**Comment by dm4** [comment]
Thanks @B1boid. PR #46 merged.
